revert bin_deploy

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -31,31 +31,30 @@ deploy_main() {
   helm upgrade laa-submit-crime-forms ./helm_deploy/. \
                           --install --wait \
                           --namespace=${K8S_NAMESPACE} \
-                          --values ./helm_deploy/values-dev.yaml \
+                          --values ./helm_deploy/values-$ENVIRONMENT.yaml \
                           --set image.repository="${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_REPOSITORY}" \
-                          --set image.tag="branch-$CIRCLE_SHA1"
+                          --set image.tag="main-$CIRCLE_SHA1"
 }
 
-deploy_main
 
-# if [[ "$CIRCLE_BRANCH" == "main" ]]; then
-#   deploy_main
-# else
-#   deploy_branch
-#   if [ $? -eq 0 ]; then
-#     echo "Deploy succeeded"
-#   else
-#     # If a previous `helm upgrade` was cancelled this could have got the release stuck in
-#     # a "pending-upgrade" state (c.f. https://stackoverflow.com/a/65135726). If so, this
-#     # can generally be fixed with a `helm rollback`, so we try that here.
-#     echo "Deploy failed. Attempting rollback"
-#     helm rollback $BRANCH_RELEASE_NAME
-#     if [ $? -eq 0 ]; then
-#       echo "Rollback succeeded. Retrying deploy"
-#       deploy_branch
-#     else
-#       echo "Rollback failed. Consider manually running 'helm delete $BRANCH_RELEASE_NAME'"
-#       exit 1
-#     fi
-#   fi
-# fi
+if [[ "$CIRCLE_BRANCH" == "main" ]]; then
+  deploy_main
+else
+  deploy_branch
+  if [ $? -eq 0 ]; then
+    echo "Deploy succeeded"
+  else
+    # If a previous `helm upgrade` was cancelled this could have got the release stuck in
+    # a "pending-upgrade" state (c.f. https://stackoverflow.com/a/65135726). If so, this
+    # can generally be fixed with a `helm rollback`, so we try that here.
+    echo "Deploy failed. Attempting rollback"
+    helm rollback $BRANCH_RELEASE_NAME
+    if [ $? -eq 0 ]; then
+      echo "Rollback succeeded. Retrying deploy"
+      deploy_branch
+    else
+      echo "Rollback failed. Consider manually running 'helm delete $BRANCH_RELEASE_NAME'"
+      exit 1
+    fi
+  fi
+fi
